name: Update & Push

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      working-directory: "Packages/godot-dev"
      run: python update.py
    - name: Run script
      working-directory: "Packages/godot-mono-dev"
      run: python update.py

    # Commit all changed files back to the repository
    - name: Push to branch
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # Optional. Commit message for the created commit.
        # Defaults to "Apply automatic changes"
        commit_message: Update packages version.
    

