name: Update & Push

on:
  schedule:
    - cron: '0 16 * * 0'  # “At 16:00 on Sunday.”
  workflow_dispatch:
  push:

jobs:
  Directories:
    name: Get directories
    runs-on: ubuntu-latest

    permissions:
      # 将默认的 GITHUB_TOKEN 赋予对仓库进行提交和推送的写权限。
      contents: write

    outputs:
      folders: ${{ steps.directories.outputs.folders }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - run: sudo apt update && sudo apt install tree jq -y
      shell: bash

    - name: Get directories
      id: directories
      run: |
        cd ./Packages
        folders=$(tree -J -d -L 1 | jq -c '.[0].contents | map(.name)')
        echo $folders
        echo "folders=$folders" >> $GITHUB_OUTPUT

  Pack-Push:
    name: "Pack & Push"
    needs: [Directories]
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix:
        folder: ${{ fromJson(needs.Directories.outputs.folders )}}
    defaults:
      run:
        working-directory: "Packages/${{ matrix.folder }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update repository
        run: |
          git pull

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: python update.py
      
      - name: Get path of nuspec
        id: nuspec
        run: |
          $nuspec = Get-ChildItem -Filter "*.nuspec" -Recurse | Select-Object -ExpandProperty FullName
          echo "nuspec=$nuspec" >> $Env:GITHUB_OUTPUT

      - name: Choco Pack
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: pack ${{ steps.nuspec.outputs.nuspec }}

      - name: Get path of package
        id: package
        run: |
          $package = Get-ChildItem -Filter "*.nupkg" -Recurse | Select-Object -ExpandProperty FullName
          echo "package=$package" >> $Env:GITHUB_OUTPUT
      
      - name: Choco Register
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: apikey --api-key ${{ secrets.CHOCOAPI }} -source https://push.chocolatey.org/

      - name: Push to Chocolately
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: push ${{ steps.package.outputs.package }} --source https://push.chocolatey.org/

      # Commit all changed files back to the repository
      - name: Push to branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # 可选。用于创建提交的提交信息。
          # 默认为"Apply automatic changes"。
          commit_message: Update ${{ matrix.folder }}